name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit

  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: |
          npm start &
          npx wait-on http://localhost:3000
      - run: npm run test:api

  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: |
          npm start &
          npx wait-on http://localhost:3000
      - run: npm run test:ui

  allure-report:
    runs-on: ubuntu-latest
    needs: [unit-tests, api-tests, ui-tests]
    if: always()

    steps:
      - uses: actions/checkout@v4
      - run: npm ci

      - uses: actions/download-artifact@v4
        with:
          path: allure-results

      - run: |
          npx allure generate allure-results -o allure-report

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report